### ISSUE TITLE
Modules don't have option to deploy in 1.7

### ISSUE THREAD

**Issue by langdonf** [Nils277/KerbalPlanetaryBaseSystems#98] opened 2019-04-13 17:18 UTC
<img width="484" alt="Screen Shot 2019-04-13 at 10 18 27 AM" src="https://user-images.githubusercontent.com/41966906/56083083-827a9680-5dd5-11e9-9847-a0ce2c2c219f.png">

Just me?  I know it hasn't been officially updated to 1.7, was just wondering if anyone else had this error. 

To everyone below me complaining, 1.7 just came out. Relax. It will be fixed. To the guy who said this was a known issue, I couldn’t find any mention of it or anyone else that had had this problem so I reported it here. Is there a better place for it?

**Comment by Doubyspk** [comment] 2019-04-13 20:31
Hi, I also missing an option to deploy in 1.7 version

**Comment by JoeGriffith** [comment] 2019-04-13 22:44
I also have this problem in 1.7. Pretty much ruins the whole thing.

**Comment by Nils277** [comment] 2019-04-14 13:43
The problem is known and caused by the update of KSP to 1.7 which in fact broke a lot of mods.
1.7 is not even out a week yet, some patience please, this will be fixed

**Comment by Nils277** [comment] 2019-05-25 16:30
Fixed with 726fb1f9deba1bace09ad7ac68dcab4549fc46e7

**Closed by Nils277** 2019-05-25 16:30 UTC
